spring:
  profiles:
    active: ${SPRING_PROFILE_ENV:qwen}

server:
  port: 9005

logging:
  level:
    root: INFO
    io.will.springai2poc: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG
